# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 306)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.pushButton_start.setObjectName("pushButton_start")
        self.lineEdit_rec_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rec_number.setGeometry(QtCore.QRect(460, 180, 110, 20))
        self.lineEdit_rec_number.setObjectName("lineEdit_rec_number")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 180, 71, 16))
        self.label.setObjectName("label")
        self.pushButton_remove_rec = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_rec.setGeometry(QtCore.QRect(460, 210, 111, 31))
        self.pushButton_remove_rec.setObjectName("pushButton_remove_rec")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(480, 100, 91, 31))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 40, 531, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_counter = QtWidgets.QLabel(self.centralwidget)
        self.label_counter.setGeometry(QtCore.QRect(40, 70, 531, 20))
        self.label_counter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_counter.setObjectName("label_counter")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(40, 150, 531, 16))
        self.label_error.setObjectName("label_error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("MainWindow", "Старт"))
        self.label.setText(_translate("MainWindow", "Номер записи"))
        self.pushButton_remove_rec.setText(_translate("MainWindow", "Удалить запись"))
        self.pushButton_stop.setText(_translate("MainWindow", "Стоп"))
        self.label_counter.setText(_translate("MainWindow", "счетчик"))
        self.label_error.setText(_translate("MainWindow", "Текст ошибки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
