# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 637)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 230, 270, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.hostLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.hostLine.setObjectName("hostLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostLine)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.s
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.portLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.portLine.setObjectName("portLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portLine)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.userLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.userLine.setObjectName("userLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userLine)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pwdLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.pwdLine.setObjectName("pwdLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pwdLine)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя сетевого устройства"))
        self.hostLine.setToolTip(_translate("Form", "Введите IP-адрес сервера или localhost"))
        self.label_2.setText(_translate("Form", "Имя порта"))
        self.portLine.setToolTip(_translate("Form", "Введите имя порта или оставьте пустым при localhost"))
        self.label_3.setText(_translate("Form", "Имя пользователя"))
        self.userLine.setToolTip(_translate("Form", "Введите имя администратора"))
        self.label_4.setText(_translate("Form", "Пароль"))
        self.pwdLine.setToolTip(_translate("Form", "Пароль администратора"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
